import { useEffect, useState } from "react"
import TracksPlayer from "./TracksPlayer.jsx"
import RadioPlayer from "./RadioPlayer.jsx"
import MixesPlayer from "./MixesPlayer.jsx"
import openLightPhotosGallery from "./LightPhotosGallery.jsx"
import "../lightSite.css"

const SOCIAL_LINKS = [["WEBSITE","https://nyxtryp.vercel.app"],["TELEGRAM","https://t.me/nyxtryp"],["YOUTUBE","https://www.youtube.com/@nyxtryp"],["TIKTOK","https://www.tiktok.com/@nyxtryp"],["INSTAGRAM","https://www.instagram.com/nyxtryp/"]]
const MENU=[["01","AUDIO"],["02","VIDEO"],["03","GUESTBOOK"],["04","VISUAL"],["05","SOCIAL"],["06","RELEASES"],["07","PHOTOS"],["08","ABOUT"]]
const COPY={
ru:{project:"НЕЗАВИСИМЫЙ ЭЛЕКТРОННЫЙ ПРОЕКТ",tag:"ВОЙДИ В НЕИЗВЕДАННОЕ.",note:"ОТКРОЙТЕ ВЕБ-ВЕРСИЮ. ВОЙДИТЕ ВО ВСЕЛЕННУЮ.",enter:"ВОЙТИ",meta:"ЭЛЕКТРОНИКА / ПОГРУЖЕНИЕ",world:"NYXTRYP / МИР",genres:"ТРАНС · ПСАЙТРАНС · АТМОСФЕРА · ДВИЖЕНИЕ",footer:"ОТКРОЙТЕ ВЕБ-ВЕРСИЮ / ВСЕЛЕННАЯ DESKTOP",headerInfo:"ПОЛНАЯ ВЕРСИЯ САЙТА ДОСТУПНА ТОЛЬКО С КОМПЬЮТЕРА ИЛИ НОУТБУКА · С УВАЖЕНИЕМ, NYXTRYP",bottomInfo:"ЭТОТ МИР СОЗДАН ДЛЯ ТЕХ, КТО ЛЮБИТ СЛУШАТЬ, СМОТРЕТЬ И ИССЛЕДОВАТЬ.",copyright:"© 2026 NYXTRYP MUSIC · ВСЕ ПРАВА ЗАЩИЩЕНЫ",menu:["АУДИО","ВИДЕО","ГОСТЕВАЯ КНИГА","ВИЗУАЛ","СОЦСЕТИ","РЕЛИЗЫ","ФОТО","О ПРОЕКТЕ"],audio:"АУДИО",tracks:"ТРЕКИ",guest:"ГОСТЕВАЯ КНИГА",soon:"СКОРО ОТКРЫТИЕ.\n\nГОСТЕВАЯ КНИГА СЕЙЧАС ГОТОВИТСЯ.\nСКОРО ВЫ СМОЖЕТЕ ОСТАВИТЬ ЗДЕСЬ СВОЙ СЛЕД.",releases:"РЕЛИЗЫ",none:"РЕЛИЗОВ ПОКА НЕТ.\n\nНОВАЯ МУЗЫКА УЖЕ СКОРО.",connect:"СВЯЗАТЬСЯ С NYXTRYP",mobile:"МОБИЛЬНАЯ / ПЛАНШЕТНАЯ ВЕРСИЯ",light:"ВЫ ИЗУЧАЕТЕ ЛЁГКУЮ ВЕРСИЮ",awaits:"ВСЕЛЕННАЯ\nЖДЁТ.",visual:["ЭТО ЛЁГКАЯ ВЕРСИЯ NYXTRYP ДЛЯ МОБИЛЬНЫХ УСТРОЙСТВ И ПЛАНШЕТОВ — СОЗДАННАЯ ДЛЯ БЫСТРОГО, ЧИСТОГО И АТМОСФЕРНОГО ОПЫТА НА НЕБОЛЬШИХ ЭКРАНАХ.","ОТКРОЙТЕ NYXTRYP НА КОМПЬЮТЕРЕ — И ВЫ УВИДИТЕ ДРУГУЮ СТОРОНУ ЭТОГО МИРА: ЖИВОЙ ЦИФРОВОЙ КОСМОС, ГДЕ САЙТ ПРЕВРАЩАЕТСЯ В ТРЁХМЕРНУЮ ВСЕЛЕННУЮ С ПРОСТРАНСТВОМ, ПЛАНЕТАМИ, ДВИЖЕНИЕМ И ИССЛЕДОВАНИЕМ.","DESKTOP-ВЕРСИЯ — ЭТО НЕ ПРОСТО ДРУГОЙ МАКЕТ. ЭТО ПОЛНЫЙ ОПЫТ NYXTRYP — ЖИВОЕ ПРОСТРАНСТВО, СОЗДАННОЕ ДЛЯ ИССЛЕДОВАНИЯ."],about:"НЕЗАВИСИМЫЙ ПРОЕКТ ЭЛЕКТРОННОЙ МУЗЫКИ, ПОСТРОЕННЫЙ ВОКРУГ АТМОСФЕРЫ, ДВИЖЕНИЯ И ПОГРУЖЕНИЯ.\n\nЗВУК ДВИЖЕТСЯ МЕЖДУ ТРАНСОМ, ПСАЙТРАНСОМ, ГЛУБОКОЙ И ОРГАНИЧНОЙ ЭЛЕКТРОННОЙ МУЗЫКОЙ — ИССЛЕДУЯ ГИПНОТИЧЕСКИЕ РИТМЫ, РАЗВИВАЮЩИЕСЯ ТЕКСТУРЫ И ЭМОЦИОНАЛЬНОЕ ПРОСТРАНСТВО.\n\nВОЙДИТЕ В МИР. ИССЛЕДУЙТЕ."},
en:{project:"INDEPENDENT ELECTRONIC PROJECT",tag:"ENTER THE UNKNOWN.",note:"OPEN THE WEB VERSION. ENTER THE UNIVERSE.",enter:"ENTER",meta:"ELECTRONIC / IMMERSIVE",world:"NYXTRYP / WORLD",genres:"TRANCE · PSYTRANCE · ATMOSPHERE · MOTION",footer:"OPEN THE WEB VERSION / DESKTOP UNIVERSE",headerInfo:"THE FULL VERSION OF THE SITE IS AVAILABLE ONLY ON A COMPUTER OR LAPTOP · WITH RESPECT, NYXTRYP",bottomInfo:"THIS WORLD IS MADE FOR THOSE WHO LOVE TO LISTEN, WATCH AND EXPLORE.",copyright:"© 2026 NYXTRYP MUSIC · ALL RIGHTS RESERVED",menu:["AUDIO","VIDEO","GUESTBOOK","VISUAL","SOCIAL","RELEASES","PHOTOS","ABOUT"],audio:"AUDIO",tracks:"TRACKS",guest:"GUESTBOOK",soon:"COMING SOON.\n\nTHE GUESTBOOK IS CURRENTLY BEING PREPARED.\nLEAVE YOUR TRACE HERE SOON.",releases:"RELEASES",none:"NO RELEASES YET.\n\nNEW MUSIC IS COMING.",connect:"CONNECT WITH NYXTRYP",mobile:"MOBILE / TABLET VERSION",light:"YOU ARE EXPLORING THE LIGHT VERSION",awaits:"THE UNIVERSE\nAWAITS.",visual:["THIS IS THE LIGHTWEIGHT MOBILE AND TABLET VERSION OF NYXTRYP — DESIGNED FOR A FAST, CLEAN AND IMMERSIVE EXPERIENCE ON SMALLER SCREENS.","OPEN NYXTRYP FROM A COMPUTER AND YOU WILL ENTER A DIFFERENT SIDE OF THE WORLD: A LIVING DIGITAL COSMOS, WHERE THE SITE BECOMES A THREE-DIMENSIONAL UNIVERSE WITH SPACE, PLANETS, MOTION AND EXPLORATION.","THE DESKTOP VERSION IS NOT JUST ANOTHER LAYOUT. IT IS THE FULL NYXTRYP EXPERIENCE — A LIVING SPACE BUILT TO BE EXPLORED."],about:"AN INDEPENDENT ELECTRONIC MUSIC PROJECT BUILT AROUND ATMOSPHERE, MOTION AND IMMERSION.\n\nTHE SOUND MOVES BETWEEN TRANCE, PSYTRANCE, DEEP AND ORGANIC ELECTRONIC MUSIC — EXPLORING HYPNOTIC RHYTHMS, EVOLVING TEXTURES AND EMOTIONAL SPACE.\n\nENTER THE WORLD. EXPLORE."},
de:{project:"UNABHÄNGIGES ELEKTRONISCHES PROJEKT",tag:"BETRITT DAS UNBEKANNTE.",note:"ÖFFNE DIE WEBVERSION. BETRITT DAS UNIVERSUM.",enter:"EINTRETEN",meta:"ELEKTRONIK / IMMERSION",world:"NYXTRYP / WELT",genres:"TRANCE · PSYTRANCE · ATMOSPHÄRE · BEWEGUNG",footer:"WEBVERSION ÖFFNEN / DESKTOP-UNIVERSUM",headerInfo:"DIE VOLLSTÄNDIGE VERSION DER WEBSITE IST NUR AUF EINEM COMPUTER ODER LAPTOP VERFÜGBAR · MIT RESPEKT, NYXTRYP",bottomInfo:"DIESE WELT IST FÜR ALLE GESCHAFFEN, DIE GERNE HÖREN, SEHEN UND ENTDECKEN.",copyright:"© 2026 NYXTRYP MUSIC · ALLE RECHTE VORBEHALTEN",menu:["AUDIO","VIDEO","GÄSTEBUCH","VISUAL","SOCIAL","RELEASES","FOTOS","ÜBER DAS PROJEKT"],audio:"AUDIO",tracks:"TRACKS",guest:"GÄSTEBUCH",soon:"KOMMT BALD.\n\nDAS GÄSTEBUCH WIRD DERZEIT VORBEREITET.\nHINTERLASSE BALD DEINE SPUR.",releases:"RELEASES",none:"NOCH KEINE RELEASES.\n\nNEUE MUSIK KOMMT BALD.",connect:"MIT NYXTRYP VERBINDEN",mobile:"MOBIL / TABLET VERSION",light:"DU ERKUNDEST DIE LIGHT-VERSION",awaits:"DAS UNIVERSUM\nWARTET.",visual:["DIES IST DIE LEICHTE MOBILE- UND TABLET-VERSION VON NYXTRYP — ENTWICKELT FÜR EIN SCHNELLES, KLARES UND IMMERSIVES ERLEBNIS AUF KLEINEREN BILDSCHIRMEN.","ÖFFNE NYXTRYP AUF EINEM COMPUTER UND DU BETRITTST EINE ANDERE SEITE DER WELT: EINEN LEBENDIGEN DIGITALEN KOSMOS, IN DEM DIE WEBSITE ZU EINEM DREIDIMENSIONALEN UNIVERSUM MIT RAUM, PLANETEN, BEWEGUNG UND ENTDECKUNG WIRD.","DIE DESKTOP-VERSION IST NICHT NUR EIN ANDERES LAYOUT. SIE IST DAS VOLLE NYXTRYP-ERLEBNIS — EIN LEBENDIGER RAUM ZUM ERKUNDEN."],about:"EIN UNABHÄNGIGES ELEKTRONISCHES MUSIKPROJEKT, AUFGEBAUT RUND UM ATMOSPHÄRE, BEWEGUNG UND IMMERSION.\n\nDER SOUND BEWEGT SICH ZWISCHEN TRANCE, PSYTRANCE, TIEFER UND ORGANISCHER ELEKTRONISCHER MUSIK."},
fr:{project:"PROJET ÉLECTRONIQUE INDÉPENDANT",tag:"ENTRE DANS L’INCONNU.",note:"OUVRE LA VERSION WEB. ENTRE DANS L'UNIVERS.",enter:"ENTRER",meta:"ÉLECTRONIQUE / IMMERSION",world:"NYXTRYP / MONDE",genres:"TRANCE · PSYTRANCE · ATMOSPHÈRE · MOUVEMENT",footer:"OUVRIR LA VERSION WEB / UNIVERS DESKTOP",headerInfo:"LA VERSION COMPLÈTE DU SITE EST DISPONIBLE UNIQUEMENT SUR UN ORDINATEUR OU UN ORDINATEUR PORTABLE · AVEC RESPECT, NYXTRYP",bottomInfo:"CE MONDE EST CRÉÉ POUR CEUX QUI AIMENT ÉCOUTER, REGARDER ET EXPLORER.",copyright:"© 2026 NYXTRYP MUSIC · TOUS DROITS RÉSERVÉS",menu:["AUDIO","VIDÉO","LIVRE D'OR","VISUEL","SOCIAL","SORTIES","PHOTOS","À PROPOS"],audio:"AUDIO",tracks:"TITRES",guest:"LIVRE D'OR",soon:"BIENTÔT DISPONIBLE.\n\nLE LIVRE D'OR EST EN PRÉPARATION.\nLAISSE BIENTÔT TA TRACE ICI.",releases:"SORTIES",none:"AUCUNE SORTIE POUR LE MOMENT.\n\nDE LA NOUVELLE MUSIQUE ARRIVE.",connect:"CONTACTER NYXTRYP",mobile:"VERSION MOBILE / TABLETTE",light:"VOUS EXPLOREZ LA VERSION LÉGÈRE",awaits:"L'UNIVERS\nATTEND.",visual:["VOICI LA VERSION LÉGÈRE DE NYXTRYP POUR MOBILE ET TABLETTE — CONÇUE POUR UNE EXPÉRIENCE RAPIDE, PURE ET IMMERSIVE SUR LES PETITS ÉCRANS.","OUVRE NYXTRYP SUR UN ORDINATEUR ET TU DÉCOUVRIRAS UNE AUTRE FACE DU MONDE : UN COSMOS NUMÉRIQUE VIVANT OÙ LE SITE DEVIENT UN UNIVERS EN TROIS DIMENSIONS.","LA VERSION DESKTOP N'EST PAS SIMPLEMENT UNE AUTRE MISE EN PAGE. C'EST L'EXPÉRIENCE NYXTRYP COMPLÈTE."],about:"UN PROJET DE MUSIQUE ÉLECTRONIQUE INDÉPENDANT CONSTRUIT AUTOUR DE L'ATMOSPHÈRE, DU MOUVEMENT ET DE L'IMMERSION.\n\nLE SON ÉVOLUE ENTRE TRANCE, PSYTRANCE ET MUSIQUE ÉLECTRONIQUE ORGANIQUE."}
}
function MenuIcon({title}){const icons={AUDIO:"🎛️",VIDEO:"▶️",GUESTBOOK:"📖",VISUAL:"🌌",SOCIAL:"🔗",RELEASES:"💿",PHOTOS:"📷",ABOUT:"💬"};return <span className={"light-row-icon icon-"+title.toLowerCase()}>{icons[title]}</span>}
function Modal({children,onClose}){return <div className="light-modal" onPointerDown={e=>e.target===e.currentTarget&&onClose()}><button className="light-close" onClick={onClose}>×</button><div className="light-modal-content">{children}</div></div>}
export default function LightSite(){
 const [entered,setEntered]=useState(false),[player,setPlayer]=useState(null),[page,setPage]=useState(null),[lang,setLang]=useState("en"); const t=COPY[lang]
 useEffect(()=>{const a=document.body.style.overflow,b=document.documentElement.style.overflow;document.body.style.overflow="auto";document.documentElement.style.overflow="auto";return()=>{document.body.style.overflow=a;document.documentElement.style.overflow=b}},[])
 const Flags=()=> <div className="light-flags"><button onClick={()=>setLang("ru")} aria-label="Русский">🇷🇺</button><button onClick={()=>setLang("en")} aria-label="English">🇬🇧</button><button onClick={()=>setLang("de")} aria-label="Deutsch">🇩🇪</button><button onClick={()=>setLang("fr")} aria-label="Français">🇫🇷</button></div>
 const open=n=>n==="photos"?openLightPhotosGallery():setPage(n)
 const key=x=>x==="AUDIO"?"audio":x==="VIDEO"?"video":x.toLowerCase()
 if(!entered)return <main className="light-site light-intro"><Flags/><div className="light-noise"/><div className="light-orbit orbit-a"/><div className="light-orbit orbit-b"/><div className="light-intro-core"><div className="light-kicker">{t.project}</div><div className="light-logo">NYXTRYP</div><div className="light-tag">{t.tag}</div><div className="light-note">{t.note}</div><button className="light-enter" onClick={()=>setEntered(true)}><span>{t.enter}</span><i>↗</i></button></div></main>
 return <main className="light-site light-home"><div className="light-stars"/><header className="light-header"><button className="light-brand" onClick={()=>setPage(null)}>NYXTRYP</button><div className="light-header-meta" data-header-info={t.headerInfo}>{t.meta}</div><Flags/></header><section className="light-hero"><div className="light-hero-line">{t.world}</div><h1 className="light-home-tag">{t.tag}</h1><p>{t.genres}</p></section><nav className="light-list">{MENU.map(([n,title],i)=><button key={title} className={"light-row "+(n==="01"?"is-featured":"")} onClick={()=>open(key(title))}><span className="light-row-number">{n}</span><span className="light-row-title">{t.menu[i]}</span><MenuIcon title={title}/></button>)}</nav><footer className="light-footer" data-bottom-info={t.bottomInfo}><span>NYXTRYP</span><span>{t.footer}</span><span className="light-copyright">{t.copyright}</span></footer>
 {page==="audio"&&<Modal onClose={()=>setPage(null)}><div className="light-index"><div className="light-modal-kicker">{t.audio}</div><button onClick={()=>setPlayer("tracks")}><strong>{t.tracks}</strong></button><button onClick={()=>setPlayer("radio")}><strong>RADIO</strong></button><button onClick={()=>setPlayer("mixes")}><strong>MIXES</strong></button></div></Modal>}
 {page==="video"&&<Modal onClose={()=>setPage(null)}><div className="light-index"><div className="light-modal-kicker">{t.menu[1]}</div><a className="light-modal-link" href="https://www.youtube.com/@nyxtryp" target="_blank" rel="noopener noreferrer"><strong>YOUTUBE</strong></a></div></Modal>}
 {page==="guestbook"&&<Modal onClose={()=>setPage(null)}><SimplePage kicker={t.world} title={t.guest} text={t.soon}/></Modal>}
 {page==="releases"&&<Modal onClose={()=>setPage(null)}><SimplePage kicker="NYXTRYP / MUSIC" title={t.releases} text={t.none}/></Modal>}
 {page==="about"&&<Modal onClose={()=>setPage(null)}><SimplePage kicker="NYXTRYP / ABOUT" title="NYXTRYP" text={t.about}/></Modal>}
 {page==="social"&&<Modal onClose={()=>setPage(null)}><div className="light-index"><div className="light-modal-kicker">{t.connect}</div>{SOCIAL_LINKS.map(([n,u])=><a className="light-modal-link" key={n} href={u} target="_blank" rel="noopener noreferrer"><strong>{n}</strong></a>)}</div></Modal>}
 {page==="visual"&&<Modal onClose={()=>setPage(null)}><div className="light-visual-page"><div className="light-modal-kicker">{t.mobile}</div><div className="light-visual-message"><div className="light-visual-eyebrow">{t.light}</div><h2>{t.awaits.split("\n").map((x,i)=><>{i>0&&<br/>}{i===1?<em>{x}</em>:x}</>)}</h2><div className="light-visual-rule"/>{t.visual.map(x=><p key={x}>{x}</p>)}<div className="light-visual-sign">NYXTRYP / DESKTOP UNIVERSE</div></div></div></Modal>}
 {player==="tracks"&&<Modal onClose={()=>setPlayer(null)}><TracksPlayer onClose={()=>setPlayer(null)}/></Modal>}{player==="radio"&&<Modal onClose={()=>setPlayer(null)}><RadioPlayer onClose={()=>setPlayer(null)}/></Modal>}{player==="mixes"&&<Modal onClose={()=>setPlayer(null)}><MixesPlayer onClose={()=>setPlayer(null)}/></Modal>}</main>}
function SimplePage({kicker,title,text}){return <div className="light-simple"><div className="light-modal-kicker">{kicker}</div><h2>{title}</h2><div className="light-rule"/><p>{text}</p></div>}